/**
 * Migration runner.
 *
 *   pnpm db:migrate          apply pending schema migrations, then (re)apply policies
 *   pnpm db:reset            DROP everything and rebuild — local development only
 *
 * Two layers, on purpose:
 *
 *  1. `migrations/sql/*` — generated by drizzle-kit from the schema. Ordinary DDL.
 *  2. `migrations/policies/*` — hand-written, IDEMPOTENT SQL that enables and forces
 *     row-level security, creates the tenant policies, attaches audit triggers, and
 *     revokes UPDATE/DELETE on append-only tables. It runs after every migration so
 *     that a newly generated table is covered the moment it exists, rather than
 *     relying on someone remembering to add a policy.
 *
 * Runs as the OWNER role, never as the application role.
 */
import { readdir, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';

const here = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(here, '..', 'migrations');

const url = process.env.DATABASE_MIGRATION_URL;
if (!url) {
  throw new Error('DATABASE_MIGRATION_URL is not set (this must be the owner role)');
}

const reset = process.argv.includes('--reset');

async function main() {
  const sql = postgres(url!, { max: 1, onnotice: () => undefined });

  try {
    if (reset) {
      if (process.env.NODE_ENV === 'production') {
        throw new Error('Refusing to reset a production database');
      }
      console.log('⚠  Dropping and recreating schema public');
      await sql.unsafe('drop schema if exists public cascade; create schema public;');
      await sql.unsafe('drop schema if exists app cascade;');
      await sql.unsafe('drop schema if exists drizzle cascade;');
      // Re-run the container init so extensions and the app role exist again.
      const init = await readFile(join(here, '..', '..', '..', 'infra', 'postgres', 'init', '01-extensions.sql'), 'utf8');
      await sql.unsafe(init);
    }

    console.log('→ Applying schema migrations');
    const db = drizzle(sql);
    await migrate(db, { migrationsFolder: join(migrationsDir, 'sql') });

    console.log('→ Applying security policies');
    const policyDir = join(migrationsDir, 'policies');
    const files = (await readdir(policyDir)).filter((f) => f.endsWith('.sql')).sort();
    for (const file of files) {
      const body = await readFile(join(policyDir, file), 'utf8');
      await sql.unsafe(body);
      console.log(`   ✓ ${file}`);
    }

    console.log('✓ Database is up to date');
  } finally {
    await sql.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
